import playwright from "playwright";
const { chromium } = playwright;
const browser = await chromium.launch();
const page = await browser.newPage();
page.on("console", (m) => console.log("[console]", m.text()));
await page.goto("http://localhost:3000/applications/demo-application/review");
await page.waitForSelector("#declaration-accurate");
await page.waitForTimeout(500);
await page.locator("#declaration-accurate").click();
await page.waitForTimeout(500);
console.log("aria-checked after:", await page.locator("#declaration-accurate").getAttribute("aria-checked"));
await browser.close();
